language: objective-c  # [sic]. Travis uses objective-c just to determine it needs to use the xcode cli
osx_image: xcode8

before_install:
  - ./fastlane/before_install.sh

script:
  - travis_retry fastlane test

notifications:
  email: false