language: objective-c  # [sic]. Travis uses objective-c just to determine it needs to use the xcode cli
osx_image: xcode8.2

# cache:
#   directories:
#     - $HOME/.sonar

branches:
  # Only run push builds for the master branch. PR builds are run nevertheless
  only: 
    - master

before_install:
  - ./fastlane/before_install.sh

script:
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then FASTLANE_EXPLICIT_OPEN_SIMULATOR=2 travis_retry fastlane pull_request; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then FASTLANE_EXPLICIT_OPEN_SIMULATOR=2 travis_retry fastlane integration; fi'

notifications:
  email: false
