language: objective-c  # [sic]. Travis uses objective-c just to determine it needs to use the xcode cli
osx_image: xcode8.2

# cache:
#   directories:
#     - $HOME/.sonar

branches:
  # Only run push builds for the master branch. PR builds are run nevertheless
  only: 
    - master

before_install:
  - ./fastlane/before_install.sh

script:
   - fastlane snapshot reset_simulators --force  # Workaround for Travis bug https://github.com/travis-ci/travis-ci/issues/7031
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then FASTLANE_EXPLICIT_OPEN_SIMULATOR=2 fastlane pull_request; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then FASTLANE_EXPLICIT_OPEN_SIMULATOR=2 fastlane integration; fi'

notifications:
  email: false
