language: objective-c  # [sic]. Travis uses objective-c just to determine it needs to use the xcode cli
osx_image: xcode8.2

# cache:
#   directories:
#     - $HOME/.sonar

before_install:
  - ./fastlane/before_install.sh

script:
  - ./fastlane/travis_runner.sh

notifications:
  email: false
